Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "n1" do |n1|
    n1.vm.box = "ubuntu/lunar64"
  end

  config.vm.define "n2" do |n2|
    n2.vm.box = "ubuntu/lunar64"
  end
  config.vm.define "n3" do |n3|
    n3.vm.box = "ubuntu/lunar64"
  end
end
